# Generated by Django 5.0.6 on 2024-06-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBook',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('idioma', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webir_app.googlebook')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webir_app.googlebook')),
            ],
        ),
    ]
