# Generated by Django 5.0.6 on 2024-06-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webir_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleBook',
            new_name='GoogleBooks',
        ),
    ]
