# Generated by Django 5.0.6 on 2024-06-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webir_app', '0002_rename_googlebook_googlebooks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Autores',
        ),
        migrations.RenameModel(
            old_name='Autor',
            new_name='Categorias',
        ),
    ]
