# Generated by Django 5.0.6 on 2024-06-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webir_app', '0003_rename_categoria_autores_rename_autor_categorias'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autores',
            table='autores',
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='googlebooks',
            table='googlebooks',
        ),
    ]
