# Generated by Django 5.0.6 on 2024-06-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webir_app', '0005_goodreads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
