# Generated by Django 5.0.6 on 2024-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webir_app', '0006_alter_autores_id_alter_categorias_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='isbn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
