# Generated by Django 5.0.6 on 2024-06-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webir_app', '0009_triagram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodreads',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
